### ISSUE TITLE
On jupyterhub, tab could allow enabling clusters

### ISSUE THREAD

**Issue by dsblank** [ipython/ipyparallel#167]
I guess there isn't a way to enable clusters for all users on jupyterhub?

Current users see this:

![screenshot from 2016-07-14 11 00 08](https://cloud.githubusercontent.com/assets/168568/16844194/2b6f4898-49b2-11e6-8699-95f784034564.png)

Could a button/link be made there that would run `ipcluster nbextension enable` for the user if installed?

**Comment by minrk** [comment]
The ipyparallel-provided command doesn't expose all of the options of the underlying commands, but you can do this for all users:

```bash
jupyter nbextension install --sys-prefix --py ipyparallel
jupyter nbextension enable --sys-prefix --py ipyparallel
jupyter serverextension enable --sys-prefix --py ipyparallel
```

**Comment by sfederow** [comment]
Is there a way to enable this so that it is **not** run as root for all users using the LocalProcessSpawner and PamAuthenticator?  In particular is there a way to have the "start" button in the "IPython Clusters" tab run the `ipcluster start` command with a specified IPython kernel?  

I have ipyparallel working when I run `ipcluster start --profile=sge` from the command line after activating a conda environment that has netifaces among other libraries installed (using your wonderful suggestion from [here](https://stackoverflow.com/questions/32204151/run-ipython-parallel-on-sge-cluster-from-local-controller-using-queue-system) to get it running on an SGE cluster).  I can then start a notebook with a kernel installed from the same conda environment used to run the `ipcluster start --profile=sge` and successfully use ipyparallel.  

However, when I try to use the "start" button in the "IPython Clusters" tab instead of running `ipcluster start --profile=sge` I can see that the process is logged via the main JupyterHub process and appears to be running with the default root kernel.  Since the root user cannot submit to our SGE cluster the ipcontroller and ipengines never get started.

I am working to distribute this to a number of users and would like to be able to use the built-in "IPython Clusters" tab instead of having everyone run their own command line `ipcluster start`.  Any assistance would be greatly appreciated!!

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

The clusters tab runs in the notebook env, but the Launcher configurations can run arbitrary commands in arbitrary envs (on arbitrary hosts), e.g. by specifying the `ipengine_cmd` and `ipcontroller_cmd` options.

There isn't any mechanism that would be choosing to run as root, though - it runs as the same user as the notebook server. Unless the notebook server itself is running as root...
