### ISSUE TITLE
Task count with `wait_interactive` on a `DirectView` seems wrong

### ISSUE THREAD

**Issue by wmayner** [ipython/ipyparallel#217]
I'm finding that when I use `wait_interactive` on a `DirectView`, the denominator is the number of engines, rather than the number of tasks. Is this by design?

System info:
```
python -c "import IPython; print(IPython.sys_info())"

{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/will/.virtualenvs/animalysis/lib/python3.4/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.6',
 'sys_executable': '/home/will/.virtualenvs/animalysis/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.2 (default, Oct  8 2014, 10:45:20) \n[GCC 4.9.1]'}
```

**Comment by minrk** [comment]
The task count is the number of discrete execution requests (messages), not the number of items in the map. This is always the number of engines for a DirectView, but can vary with a LoadBalancedView, depending on chunksize (default=1, where n_tasks = n_items). So it is by design, but that doesn't necessarily mean it's how it should work.

**Comment by wmayner** [comment]
Ah, I see. So we should instead use `len(asnyc_map_result)`?

**Comment by jorpilo** [comment]
+1 I think the current behaviour is really confusing as it doesn't represent the amount of work done. I send 125 long tasks to 4 workers, the current implementation only shows n/4 which basically ends at the same time, instead of the 125 tasks gradually ending.

Any workaround to show the number of tasks?

**Comment by minrk** [comment]
We can update the code to show the 'true' number, but it will still only get updated one time per message, so the lack of granular updates would be the same, it would just go 0, 30, 60, 90, 120 instead of 0, 1, 2, 3, 4, and the updates would come at the same times.

As I mentioned above, if you want more granular updates, use LoadBalancedView. You can tune chunksize for the appropriate level of feedback that you want (In my experience, around 1 second per chunk is good.

**Comment by minrk** [comment]
#655 uses the item count for the length and progress, rather than the message count
