### ISSUE TITLE
Feature proposal: Launch ipcluster from python

### ISSUE THREAD

**Issue by twiecki** [ipython/ipyparallel#22]
For simple parallelization requirements on a single host it is often an extra burden (especially when designing APIs) to require the user to launch `ipcluster`. If instead I could also launch these from within my Python library it could be a very nice replacement for `multiprocessing` which supports this mode. Specifically, if my library is using multiprocessing the user doesn't have to care about anything and get single-machine parallelization for free. The problem is that `multiprocessing` sucks and I'd much rather use `ipyparallel` for this as well.

I suppose there might be an unsupported way to do this already by importing `ipcluster` somehow.

Anyway, I think that would be useful for certain problems.

**Comment by minrk** [comment]
Agreed. For a summary of the plans I have in my head:

- make ipcluster a service, rather than a script
- ipcluster would manage many instances of controllers and engine groups, not just one at a time
- talk to it via REST API
- add a Python wrapper for the service API, so you can start/stop clusters 

This would alleviate a lot of the annoyances of ipcluster, I think.

In the meantime, there's [ipython-cluster-helper](https://github.com/roryk/ipython-cluster-helper), which provides much of what you describe, I think.

**Comment by twiecki** [comment]
Thanks. I think `ipython-cluster-helper` really only works with cluster schedulers, rather than locally.

**Comment by twiecki** [comment]
@minrk just wondering if perhaps there's a WIP version I could try.

**Comment by minrk** [comment]
Sorry, not yet.

**Comment by jakirkham** [comment]
Also, in favor of this proposal, currently I find myself having to shell out the launch and shutdown the cluster. It would be great not to have to do that.

**Comment by BitMechanic** [comment]
Hey @minrk, would it not work just to start a cluster from a multiprocess.process?

**Comment by BitMechanic** [comment]
So;

```
def worker():
      call("ipcluster start -n 4")

def main():

    initipy = multiprocessing.Process(target=worker)
    initipy.start()
  
    rc = ipp.Client()

if __name__ == "__main__":
    main()

```

**Comment by minrk** [comment]
Yes, that definitely works. It wouldn't be much more than that, though I would probably invoke Launches directly in process, rather than shelling out to ipcluster, which in turn shells out to ipengine, etc. I'm mainly thinking of a nice, clean API that allows automatic cleanup, etc., so you could do things like:

```python
with ipp.cluster(n=4) as rc:
    view = rc.load_balanced_view()
...
```

**Comment by BitMechanic** [comment]
Is there a way to query the engines etc in python, so that you can check when an engine has finished booting up, what its currently doing? The booting up signal is particularly important from python, because we don't want someone using a python based GUI to try and use an engine that isn't yet there.

**Comment by BitMechanic** [comment]
Great, thanks @minrk
