### ISSUE TITLE
is_local_ip failing

### ISSUE THREAD

**Issue by rjplevin** [ipython/ipyparallel#246]
I'm running the current ipyparallel master in develop mode on a Mac (10.10.5), anaconda python 2.7.

I'm getting a spurious ssh-related warning: I'm running on the local machine, not using ssh. Line 430 in client.py is checking if my hostname (not IP addr) is a local IP, and failing. In line 419, it has already disambiguated the hostname to u'127.0.0.1', but it calls is_ip_local(location) rather than is_ip_local(addr), thus failing. However this is within a test that addr == localhost(), so it's not clear to me what the point is. (I'd fix it and submit a pull request if I understood it completely!)

**Comment by minrk** [comment]
Thanks, it's a bit complicated. `addr` is the address where the controller is listening. `location` is an address where the controller *is* (`socket.gethostname()` in master, a somewhat random public ip address in previous releases). This block of code is covering:

```python
if controller is listening on its own localhost (addr):
    if controller is running on this machine (location):
        connect directly to localhost
    else:
        tunnel with ssh
```

The problem arrises because of recent changes that use hostname in location, rather than ip addresses everywhere. I missed a spot, but #252 should fix it.
