### ISSUE TITLE
Client does not honor keyfile

### ISSUE THREAD

**Issue by ktong** [ipython/ipyparallel#268]
Expect 'Client(file_path, keyfile=key_path)' creates a client with session key from keyfile but not.

**Comment by minrk** [comment]
Hm, I'll have to check the keyfile arg handling in jupyter-client, I don't think I've seen it used before. Are you not using a normal connection file with the key as a field?

**Comment by ktong** [comment]
we deployed a cluster in GKE. All field excepts key we just put in config Map. For key, we have to put it in secret to keep it safe. ipcontroll and  ipengine can start with --keyfile arg. Only Client does not honor it.

**Comment by minrk** [comment]
Is there a reason to split the connection file into config and secret, rather than putting the whole connection file in a secret because it contains auth info? The connection file isn't useful without the key, so it doesn't seem useful to separate them since they must always be recombined to be used.

**Comment by ktong** [comment]
Yes, all connection files can be put into secret. However, we split it with some reasons:
1. We use dedicated manual process to deploy secret, so we do not need put passwords into circleCI. Keep secret simple then we can reduce times of redeployment.

2. The host information in connection file can not get in secret deployment because it derives dynamically.
