### ISSUE TITLE
local variables in engines

### ISSUE THREAD

**Issue by Yoonsen** [ipython/ipyparallel#272]
There are 60 engines with a varible "ft" which has a different value for  each, inside a Flask application.

When started with "python application.py" everything works nicely, and queries are executed as they should. However when the app is started with uwsgi, queries stop with the message Error "ft" is not defined. What could be the cause of this?

ft is referenced in a 

result = client.apply(lambda: function(ft,...)).get()

If instead of the apply(), the code is put inside quotes and run with execute everything is fine:

client.execute("res = function(ft,..)")
result = client['res']

While execute() is ok, it seems vulnerable to injections.

Any hints as to solve this with apply()?

Best,
Lars

**Comment by minrk** [comment]
I'm not sure precisely how uwsgi would cause such a thing. Is it possible to see a complete example that demonstrates the issue?

It probably has to do with detecting closures on `ft`, e.g. if there is an `ft` locally in the module calling `client.apply`. Different things can have subtle impacts on how this resolves, which is probably why it happens only in some environments.

One way around it is to avoid any possible detection of a closure by using `parallel.Reference`:

```python
import ipyparallel as ipp
result = client.apply(lambda ft: f(ft, ...), ipp.Reference('ft'))
```

This makes the reference to remote `ft` explicit, rather than implicit on an unresolved closure.

Execute would only be vulnerable to injection if user strings are being used to assemble the code to execute. If you are building the commands yourself it shouldn't be an issue, but I agree that apply is generally more desirable where available.

**Comment by Yoonsen** [comment]
Thanks! The ipp.Reference() did the trick. 

It has probably something to do with closures, as you suggest. The module where "ft" is referenced is not the one importing ipyparallel, which happens in another imported module. So module A imports B which in turn imports ipyparallel, and defines and initializes the clients.

The call that causes trouble with uwsgi, but works with flask directly is this.
Module A (the front end module) calls apply() via B:

B.clients[:].apply(lambda: f(ft,...))

So that 'ft' is first referenced in A, then sent to B (?) before dispatched to the clients. One of  the contexts catches 'ft' on its way, or so it seems.

Anyway, ipp.Reference() is a clear and explicit way of doing it.

And, yes, the parameters will come directly from user input.

Best,
Lars
