### ISSUE TITLE
ipyparallel + numba - python crash

### ISSUE THREAD

**Issue by dmitryelj** [ipython/ipyparallel#299]
Hi all,
Thanks for the cool product.

I'm trying ipyparallel with numba, and always getting a python crash. Tested on OSX, Windows, Python2 and Python3.

Code:

```
import ipyparallel as ipp

rc = ipp.Client()
dv = rc[:]

with dv.sync_imports():
  import math
  import numba

def test_func1(n):
    return n + 42

@numba.jit
def test_func2(n):
    return n + 42

values = [1, 2, 3, 4, 5]

# This works
res = dv.map_sync(test_func1, values)
print("R1", res)

# Here I getting the crash
res = dv.map_sync(test_func2, values)
print("R2", res)
````

What I am doing wrong? Is ipyparallel in general compatible with numba?
Thanks.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Sorry for not responding in a reasonable amount of time!

It looks like this issue is resolved with current numba (0.53.1) and ipython parallel (d72a7312d1bd9c77a86542d03e34e11817631a57).

Feel free to open a new Issue if you are still having this trouble.
