### ISSUE TITLE
Delaying tests output after running ipcluster on travis (Mac OS)

### ISSUE THREAD

**Issue by b5y** [ipython/ipyparallel#348]
Hello,

We are using ipyparallel in our [project](https://github.com/elfi-dev/elfi) and starting from September have issues on Mac OS environment. Namely, [tests pass up to running ipyparallel](https://travis-ci.org/elfi-dev/elfi/jobs/462836827) (we use [native, multiprocessing and ipyparallel clients](https://github.com/elfi-dev/elfi/blob/travis/tests/conftest.py#L35)) and at some point it delays. Since travis stops any tests which don’t output anything after 10 minutes, we get crashing tests every time. Increasing time by `travis_wait` doesn’t help at all. Changing packages versions doesn’t help as well. Re-implementing [running](https://github.com/elfi-dev/elfi/blob/dev/.travis.yml#L28) `ipcluster` ([dev](https://github.com/elfi-dev/elfi/blob/dev/tests/conftest.py#L46)) doesn't help also ([travis branch](https://github.com/elfi-dev/elfi/blob/travis/tests/conftest.py#L46)).

Please consider our issue. Any help will be highly appreciated.

Sincerely yours,
Mehti

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Sorry for not responding in a reasonable amount of time!

There have been issues with hangs due to changes in IPython and ipykernel that IPython Parallel hasn't kept up with. I *believe* all such issues are resolved, and I'll ship a prerelease of ipyparallel 7 shortly.  Please feel free to open a new Issue if you are still having this trouble after IPP 7 ships.
