### ISSUE TITLE
Costarting a ipcontroller and ipengines along the Python script in a single job script

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#370]
## Question
Is it possible to start a multi node executor from within a jobscript where a Python script is called that has to connect to the excutor?

## Example
For example, this is possible with a `mpi4py.futures. MPIPoolExecutor` like:
```
#!/bin/sh
#PBS -l nodes=5:ppn=20
#PBS -V
#PBS -N test

cd $PBS_O_WORKDIR

mpiexec -n 100 /home/basnijholt/miniconda3/bin/python -m mpi4py.futures run_learner.py  # this script uses `MPIPoolExecutor`
```
However, I cannot use the `MPIPoolExecutor` for my application (see below).
I believe this should be doable with `ipyparallel` too, something like:
```
#!/bin/sh
#PBS -l nodes=5:ppn=20
#PBS -V
#PBS -N test

cd $PBS_O_WORKDIR

profile=job_${SLURM_JOB_ID}_$(hostname)

echo "Creating profile ${profile}"
ipython profile create ${profile}

echo "Launching controller"
ipcontroller --ip="*" --profile=${profile} --log-to-file &
sleep 10

echo "Launching engines"
mpiexec -n 99 ipengine --profile=${profile} --mpi --cluster-id='' --log-to-file &  # Note that this uses `mpi` but I don't need this, I would even like to avoid it.

echo "Starting the Python script"
/home/basnijholt/miniconda3/bin/python run_learner.py ${profile} 99
```

This doesn't completely work, unfortunately. Is this the right approach? Or is there an easier thing to try?

## Why (context)
I wrote a tool called [`adaptive-scheduler`](http://adaptive-scheduler.readthedocs.io) that manages creating and running job scripts for running simulations using the [Adaptive package](http://adaptive.readthedocs.io) on 10k-50k cores. I am using `mpi4py.futures. MPIPoolExecutor`, because I want a executor that I can just start in the same job script as where I run the Python code. However, I am having issues because code that already uses MPI doesn't work with the `MPIPoolExecutor` I am trying to do a similar thing with `ipyparallel` (or [distributed](https://github.com/dask/distributed/issues/2769)).

**Comment by minrk** [comment]
Yes, this is possible!

I should point out that it ought to be fine to skip the `--mpi` argument if you want to call mpi init yourself. All this does is [import mpi4py.MPI](https://github.com/ipython/ipyparallel/blob/f2c10970b782b60b2f2ec04e95ab88d204d6c6b9/ipyparallel/engine/engine.py#L33-L35), which calls MPI_Init, though, so it seems unlikely to be harmful unless you really need to be the one to call MPI_Init. There's no cost to leaving this out other than the IPython ranks will not match MPI ranks (usually doesn't matter and was the case for a long time).

What I've done is to use a jobarray so that instead of running the processes in the background, they are distinct jobs:

```bash
#PBS -t 1-3
case "${PBS_ARRAYID}" in
    "0" )
        # job 0 is the controller
        ipcontroller ...
    ;;
    "1" )
        # job 1 is the script
        sleep 30
        script...
    ;;
    * )
        # the remainer is the engine
        aprun -n 99 ipengine
    ;;
esac
```

Alternately, you can write a little Python script that you mpiexec and do this by mpi rank:

```python
import sys
import time
from mpi4py import MPI

rank = MPI.COMM_WORLD.rank
size = MPI.COMM_WORLD.size

def do_some_work(comm):
    print(f"Doing some work: {comm.rank} / {comm.size}")
    return comm.rank

def make_comm():
    from mpi4py import MPI
    global comm
    group = MPI.COMM_WORLD.group.Excl([0, 1])

    comm = MPI.COMM_WORLD.Create_group(group)
    return repr(comm)

if rank == 0:
    print("rank 0: starting controller")
    sys.stdout.flush()
    from ipyparallel.apps.ipcontrollerapp import launch_new_instance
    launch_new_instance(['--profile=abc'])
elif rank == 1:
    print("rank 1: starting script")
    sys.stdout.flush()
    time.sleep(3)
    import ipyparallel as ipp
    rc = ipp.Client(profile='abc')
    expected_size = size - 2
    while len(rc) < expected_size:
        print(f"Connected {len(rc)}/{expected_size} engines")
        sys.stdout.flush()
        time.sleep(1)
    dv = rc[:]
    # create a comm for jobs 2+ (only engines)
    print(dv.apply_sync(make_comm))
    r_comm = ipp.Reference('comm')
    results = dv.apply_sync(do_some_work, r_comm)
    print(f"results: {results}")
    print("finished, shutting down")
    sys.stdout.flush()
    rc.shutdown(hub=True)
else:
    print(f"rank {rank}: starting engine")
    sys.stdout.flush()
    time.sleep(3)
    from ipyparallel.apps.ipengineapp import launch_new_instance
    launch_new_instance(['--profile=abc'])
```

Then your pbs job just mpiexecs this script (after any initialization and before any cleanup).

- mpi rank 0 is the controller
- mpi rank 1 is the client, submitting the real workload
- remaining mpi ranks launch engines
- a sub-group comm is created for all the engines so that you can do mpi global operations across the engines now that COMM_WORLD includes two jobs that you want to leave alone.
