### ISSUE TITLE
Is load_balanced_view thread-safe?

### ISSUE THREAD

**Issue by bluescarni** [ipython/ipyparallel#387]
Can I use a ``load_balanced_view`` instance from multiple threads concurrently? Specifically, I need to invoke concurrently the ``apply_async()`` method.

**Comment by minrk** [comment]
I'm inclined to say no, though I'm not sure there are any issues. There is already lots of thread coordination because all IO happens in a single background thread (no sends or receives actually happen from the thread where `apply` is called).

Feel free to give it a try, but if you encounter issues try creating multiple *clients* to avoid sharing state across threads.
