### ISSUE TITLE
May I know how to print log in engine

### ISSUE THREAD

**Issue by cometta** [ipython/ipyparallel#401]
May I know when the code is running in each engine, i try logger.info(..) or print(..) but nothing print out to the console. Is there any guide on how to use logging for ipyparallel?

**Comment by minrk** [comment]
If you want to write to the terminal, you can print to `sys.__stdout__` (or stderr). If you configure a logger with a StreamHandler on `sys.stdout` it will be captured in the task output and readable in the client, or `sys.__stdout__` it will go to the engine's termina.

**Comment by stefan-girlich** [comment]
@minrk Could you please providing a hint how to log messages from parallel code to a Jupyter Notebook?
Errors in functions which are executed in parallel are currently a complete black box for me and probably also other ipyparallel users. Maybe a logging recipe/tutorial in the docs could be helpful.

### Context
I'm currently executing a custom function based on the example code on https://ipyparallel.readthedocs.io/en/latest/ . A traceback for a `ZeroDivisionError` pops up without any line numbers, so finding the root cause without being able to log is not trivial.

### Environment

Jupyter Notebook 6.4.6
Python 3.9
ipyparallel 8.0.0

### Code
```
def _log_stuff(dummy_arg):
    print('>>>>> print')
    
    from IPython.config import Application
    log = Application.instance().log
    log.critical('>>>>> log.critical')
    
    import sys
    sys.__stdout__.write('>>>>> sys.__stdout__.write')

    # omitted: code that throws ZeroDivisionError

with ipp.Cluster() as rc:
    view = rc.load_balanced_view()
    asyncresult = view.map_async(_log_stuff, [1,2,3])
    asyncresult.wait_interactive()
    result = asyncresult.get()
```

**Comment by minrk** [comment]
Writing to the low-level `sys.__stdout__` or `Application.log` is explicitly asking to write to the original, _not_ redirected output of the process, which is how I interpreted this issue.

Printing to regular stdout/stderr will get captured, and can be viewed with `asyncresult.display_outputs()`. It can be viewed live, with:

```python
with asyncresult.stream_output():
    asyncresult.wait_interactive()
```

I definitely need to add some good debugging examples to the docs.
