### ISSUE TITLE
The variable in %%time magic cell is not accessable outside

### ISSUE THREAD

**Issue by caffett** [ipython/ipyparallel#437]
<img width="1058" alt="Screen Shot 2021-01-21 at 5 58 03 PM" src="https://user-images.githubusercontent.com/11462215/105422860-778f9f80-5c12-11eb-82eb-1ac203a45a05.png">

Is such behavior on purpose?

**Comment by minrk** [comment]
This is not really a question for IPython Parallel, since this is IPython's own behavior (the ipyparallel code has no effect), but this is not the behavior I see:

<img width="562" alt="Screen Shot 2021-06-04 at 15 57 36" src="https://user-images.githubusercontent.com/151929/120812854-aa955880-c54d-11eb-9632-160926ec6a21.png">

Make sure your IPython is up to date (mine is 7.24.1)
