### ISSUE TITLE
Docker containers for ipyparallel

### ISSUE THREAD

**Issue by 0x0L** [ipython/ipyparallel#51]
I wrote a pair of Dockerfile to make it easy to deploy ipyparallel clusters with containers. The design is to run seperate containers for the controller, the engines (several of them in a single container) and the clients. All cluster communications are tunnelled through SSH so you only need to open 1 port on the docker host of the controller and that's it.

I don't know if this is the right place but I think people might find it useful:
https://github.com/0x0L/jupyter-cluster

**Comment by minrk** [comment]
Cool! I think it's hard to figure what might actually be useful as a Dockerfile in this project. I see two cases:

1. as examples, which people can take and modify for their own uses
2. as base images, for people to inherit from / extend

After working on a variety of base images in a few places, I think that base images of packages like IPython and Jupyter have little to no usefulness, since a base image of ipyparallel necessarily gets you stuck with a particular Python implementation (maybe you want to use conda, maybe python 2, etc.), and if any one decision like that isn't what you want, the whole thing is useless. But a Dockerfile as a reference example is great.

As it stands, I'm happy to increase the visibility of your own project, rather than build something in this repo.

**Comment by 0x0L** [comment]
@minrk I completely agree with you.

Maybe I should extract the parts relevant for the cluster stuff to work based on this copying and mounting of files and make a pull request to the jupyter docker stacks repo. IMO it makes sense to have nice defaults for building clusters over SSH.
