### ISSUE TITLE
Lepton FLIR SDK PT

### ISSUE THREAD

**Issue by Smartgalpj** [ipython/ipyparallel#517]
I want to record 6 parallel videos using FLIR Lepton Cameras. I want to use python for that. I used Threading but i am able to record one video only at one time.  Can somebody help me regarding this matter

**Comment by minrk** [comment]
While IPython Parallel may be useful for this, I think it will probably be best to ask somewhere that folks know about the cameras you are using and their APIs, rather than on one particular parallel computing tool.

You'd need to identify *why* using threads doesn't work - it it because of the GIL? Or process-global state? If so, then using IPython Parallel (or multiprocessing, etc.) to run the same thing in processes instead of threads might be enough. But it could be something totally else, and I couldn't begin to investigate.

**Comment by Smartgalpj** [comment]
Dear _Minrk......I am using PureThermal Mini - FLIR Lepton Smart I/O Module by GetLab and software tool is LEPTON USER APP. Please explain more if possible.

**Comment by minrk** [comment]
I'm sorry, I don't know what any of those things are, so can't help. This is a place for discussing the IPython Parallel software, not cameras. I'd recommend asking in a forum about those tools.
