### ISSUE TITLE
concurrent.futures compatibility (IPEP 19)

### ISSUE THREAD

**Issue by minrk** [ipython/ipyparallel#53]
@aarchiba opened ipython/ipython#8893

Since concurrent.futures is standard in python >=3.4 and backported to python 2.7, it is a good way to write portable parallel code. Algorithms that support parallelism can take a pool argument and work with whatever form of parallelism the user chooses - except not IPython parallelism, right now. It would be valuable to add an Executor/Future compatibility layer.

**Comment by minrk** [comment]
@aarchiba I really want this. I even started writing it a long time ago, but had to move on to other things. Hopefully I, or someone else, will get a chance to do it soon.

**Comment by aarchiba** [comment]
Well, since I kind of need it now and I just wrote an MPI-based Executor, maybe the thing to do is write a standalone wrapper module; it can go into ipyparallel when it's ready. I don't actually need the callback thing (yet? actually it would be nice), which is the only thing that wants modifications to ipyparallel.

**Comment by minrk** [comment]
Yup, a simple wrapper exposing the right API would be the place to start. If you are working on that, feel free to link to it here.

**Comment by aarchiba** [comment]
See https://github.com/aarchiba/futuretools . Needs more testing (e.g. workers appearing and disappearing, cleanliness of shutdown).

**Comment by aarchiba** [comment]
In terms of what would be needed to improve/simplify the wrapper, the main thing is that right now it has to poll - check the AsyncResults repeatedly to see if any have finished yet. Client.wait() almost does the right thing, except that I want to wait until any result is available - including one from a request that hadn't been submitted when I start waiting. But since Client.wait() has to poll anyway there's not too much to be gained here.

**Comment by minrk** [comment]
That's awesome!

What I would do is probably subclass Client and hook up ZMQStreams on the zmq sockets and run a tornado IOLoop in a thread. That way, callbacks will fire as zmq messages arrive, rather than ever calling `Client.wait`. I'm sure that upon subclassing I would find a few methods to split up differently for re-use. 

Are you interested in tackling that? This sounds pretty fun to me, but I'm not sure when I'll get a chance to put it together.

**Comment by aarchiba** [comment]
If tornado IOLoop gives you a poll-free way to wait on messages, then it should be used to implement Client.wait(). In fact the thing to do would be to generalize Client.wait() to permit waiting for any message, as well as all messages. I haven't used tornado or zmq directly at all, so it'd take me a little while to get up to speed. For the moment I need to do some tests to see how nestle (python nested sampling) behaves with larger numbers of cores.

**Comment by aarchiba** [comment]
I think it makes sense to create a PR to include this code. I'm having trouble getting ipyparallel working from git, though. What are its dependencies? pyzmq, obviously, but I'm getting complaints about a missing ipykernel module.

**Comment by minrk** [comment]
`pip install -e .` should get all the dependencies. I think it's just ipykernel, though.

**Comment by minrk** [comment]
@aarchiba do you think you may have a chance to work on this? I added some Future support in pyzmq recently, so now I have some ideas for how this might work.

**Comment by minrk** [comment]
I might take a stab at making Client's use IOLoop and Futures internally this weekend. That should clear much of the path for wrapping a view in an Executor interface.
