### ISSUE TITLE
Cost too many kernel time

### ISSUE THREAD

**Issue by GF-Huang** [ipython/ipyparallel#541]
Code:

![image](https://user-images.githubusercontent.com/4510984/128155191-be051472-d203-40e9-a70f-38c7e03f247d.png)

When `push` a `pandas.DataFrame` with shape `(249, 3861)`, all cost are `normal`:

![image](https://user-images.githubusercontent.com/4510984/128154447-5b2df2d7-f97a-4463-bf38-223ec38c86ee.png)

When `push` a `pandas.DataFrame` with shape `(502, 3861)`, more than half cost are `kernel`:

![image](https://user-images.githubusercontent.com/4510984/128155092-5e948167-ce0d-4477-950c-4e1b24678f59.png)

### The key problem is that when the length of `df` is doubled, the time consumption will increase many times. When `(249, 3861)` it cost about 2 hours, but when `(502, 3861)` it cost more than 7 hours and still running, so I interrupt it.

The CPU bar colors means:

![image](https://user-images.githubusercontent.com/4510984/128154985-a91dc4b2-5ea3-440a-8548-8b1c90d9837a.png)

**Comment by minrk** [comment]
Since there's a good chance this has to do with pandas, it's hard to diagnose without a reproducible example. We would at least need to see what `compute_cv` does. You can try exploring what the engines are doing at the syscall level with `strace -c -p ${engine_pid}` and maybe comparing the results.

**Comment by GF-Huang** [comment]
I found that caused by `statsmodels.tsa.adfuller(...)`, which makes multi-process calls.
