### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipyparallel#73]
Appears this is dependent on a few things that aren't explicitly stated, but the requirements and version constraints are unclear as they are not listed in `setup.py`.

* `notebook` [ipyparallel/nbextension/handlers.py#L12-L14]( https://github.com/ipython/ipyparallel/blob/master/ipyparallel/nbextension/handlers.py#L12-L14 )
* `nose` [ipyparallel/tests/\_\_init\_\_.py#L12]( https://github.com/ipython/ipyparallel/blob/master/ipyparallel/tests/__init__.py#L12 )

If these are not hard requirements, maybe they should be locally imported or conditionally imported so as to avoid issues when importing things from `ipyparallel`. Admittedly, not importing those modules seems to avoid the issue presented by them.

**Comment by minrk** [comment]
nose is a testing dependency, not an install dependency. Similarly, notebook is not a dependency, it is only needed if you want to use the optional nbextension with the notebook. Currently, there is no version requirement on the notebook because it is compatible with all versions of that package that exist.

**Comment by jakirkham** [comment]
Sure, however it is still nice to be able to do a cursory glance over `setup.py` and see the requirements even if they are optional. I have add the PR above ( https://github.com/ipython/ipyparallel/pull/74 ) to add these as test and extra requirements. Additionally, it allows one to use a test suite.
