### ISSUE TITLE
BroadcastView map Not Implemented

### ISSUE THREAD

**Issue by dalbabur** [ipython/ipyparallel#861]
The documentation made it seem like BroadcastView.map had been implemented. Is this feature coming?

**Comment by minrk** [comment]
I don't think anyone is working on it at the moment, but it should be possible.

**Comment by dalbabur** [comment]
What would it take to implement it? I could attempt to with some directions.

**Comment by minrk** [comment]
map needs to partition inputs, so that each engine gets its chunk of the input sequence(s), which is done [here](https://github.com/ipython/ipyparallel/blob/ae1191b83563728076236d30a03cc89a6ac4707b/ipyparallel/client/remotefunction.py#L277-L304). In DirectView, this is implemented by partitioning the input in the _client_ and then sending a different message to each endpoint.

In BroadcastView, the client sends just one message (that's kind of its whole deal), so the partitioning would need to be handled in the [BroadcastScheduler](https://github.com/ipython/ipyparallel/blob/8.6.1/ipyparallel/controller/broadcast_scheduler.py), instead. Reconstruction could either happen in the scheduler, or only aggregated in the scheduler and reconstructed finally in the client.

Perhaps the simplest implementation would be to still _compute_ the partition in the client, but then send _all_ partitions to the scheduler. Then, as each scheduler relays its messages, it selects the subset of chunks it needs to send along each path, and returns the results in a similar shape for the client to reconstruct.

All that said, you _can_ use BroadcastView to run maps today, as long as you do the partitioning separately, as either SPMD-style partitioning on engines (works best for BroadcastView), or via e.g. `DirectView.scatter`.

[here's a notebook](https://gist.github.com/minrk/a8ee8c128bf4076414d11eacdc91b325) that implements map by combining BroadcastView and DirectView. We could actually ship a simplest-possible `BroadcastView.map` that is exactly the `broadcast_map` in that notebook (with some more unique temp variable names to avoid collisions). It's not as efficient as a 'true' Broadcast Map, but it does work, and can always be optimized later.
