### ISSUE TITLE
IPykernel 7 compatibility

### ISSUE THREAD

**Issue by Carreau** [ipython/ipyparallel#895]
It looks like ipyparallel is not compatible with ipykernel 7, 

Unfortunately I've not been following the development, and the previous maintainer stepped down a few month ago, and I'm afraid of the 6.x and 7.x branch diverging. 

I would love to get some help get the downstream testing passing on all projects that depends on ipykernel.

cf https://github.com/ipython/ipykernel/issues/1222

**Comment by minrk** [comment]
Thanks, I think I can work on this this week.

**Comment by minrk** [comment]
I think I've tracked it down to the incomplete assumption of async sockets in the updates to IOThread. Looking into more detail, but I think the fix belongs in ipykernel because there's a mixture of sync and async use of sockets, relying on the _assumption_ that async zmq sends are eager and don't need to be awaited.

**Comment by Carreau** [comment]
I do trust you, I haven't followed what has append in ipykernel, and I'm mostly trying to not have everything fall appart.

**Comment by minrk** [comment]
Looks like it's a little more complicated than that in that ipyparallel relied on support for `shell_streams` as a _list_ of sockets on which to handle shell messages, and either the anyio or subshell work removed the ability to handle multiple sockets. That will probably need at least some work on this side, possibly both.

**Comment by minrk** [comment]
Thinking out loud about how to address the single socket issue

Two choices are:

1. restore support for a _list_ of shell sockets in ipykernel. This makes less sense for ipykernel now that control has its own special handling, and is prone to feature removal, as has been done in ipykernel main
1. let ipykernel keep a single socket, and implement a simple proxy in ipyparallel to funnel down to the single socket. This will perhaps be the easiest to maintain because ipykernel doesn't need to support a feature it doesn't use, at the expense of adding an inproc socket hop on top of the one already added for subshells.

I'm leaning toward the latter, which I think wouldn't need any change from ipykernel

**Comment by minrk** [comment]
I was wrong about that, ipyparallel uses one socket connected to multiple URLs, so setting `shell_socket` works okay
